apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: unhwjm80t-python 
  janus-idp.io/tekton: unhwjm80t-python
  backstage.io/kubernetes-id: unhwjm80t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: unhwjm80t-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml